In [34]:
import pandas as pd

from gsm_benchmarker.results_analyser.utils import pandas_to_latex

from results_notebook_setup import load_results, significant_models

In [2]:
N_BOOT = 2000

In [3]:
results_loader = load_results(n_boot=N_BOOT)
full_results = results_loader.full_results

100%|██████████| 2/2 [00:02<00:00,  1.03s/it]
100%|██████████| 2/2 [00:01<00:00,  1.91it/s]
100%|██████████| 2/2 [00:01<00:00,  1.73it/s]
100%|██████████| 2/2 [00:00<00:00,  3.14it/s]
100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

In [4]:
boots = {
    'GLMM1': {},
    'GLMM2': {},
}

for prompt_result in full_results.values():
    boots['GLMM1'][prompt_result.short_label] = prompt_result.mres.bootstrap_glmm1
    boots['GLMM2'][prompt_result.short_label] = prompt_result.mres.bootstrap_glmm2

In [5]:
def combine_prompt_boots(glmm_key, effect):
    return pd.concat({key: value.summary_df.xs(effect, level=1) for key, value in boots[glmm_key].items()}, axis=0, names=['prompt', 'model'])

boots_combined_dict = {
    'GLMM1-is_variant': combine_prompt_boots('GLMM1', 'is_variant'),
    'GLMM2-is_variant': combine_prompt_boots('GLMM2', 'is_variant'),
    'GLMM2-gamma_c': combine_prompt_boots('GLMM2', 'gamma_c')
}

In [6]:
boots_combined = pd.concat(boots_combined_dict, names=['test'])
boots_combined

                                                           boot_ci_upper_log  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                 -0.037108
                                 Meta-Llama-3-8B                   -0.096309
                                 Meta-Llama-3-8B-Instruct           0.065518
                                 Mistral-7B-Instruct-v0.1          -0.089163
                                 Mistral-7B-Instruct-v0.3           0.036228
...                                                                      ...
GLMM2-gamma_c    code-structured gemma-2-2b                         0.169949
                                 gemma-2-9b                         0.152930
                                 gemma-2b                           0.148986
                                 gemma-7b-it                        0.115809
                                 phi-2                              0.193958

                                                           boot_ci_lower_log  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                 -1.636772
                                 Meta-Llama-3-8B                   -1.374645
                                 Meta-Llama-3-8B-Instruct          -1.541850
                                 Mistral-7B-Instruct-v0.1          -1.278804
                                 Mistral-7B-Instruct-v0.3          -1.078176
...                                                                      ...
GLMM2-gamma_c    code-structured gemma-2-2b                        -0.226863
                                 gemma-2-9b                        -0.292218
                                 gemma-2b                          -0.232739
                                 gemma-7b-it                       -0.428509
                                 phi-2                             -0.221453

                                                           boot_se_log  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1            0.411317
                                 Meta-Llama-3-8B              0.319634
                                 Meta-Llama-3-8B-Instruct     0.401929
                                 Mistral-7B-Instruct-v0.1     0.300793
                                 Mistral-7B-Instruct-v0.3     0.283162
...                                                                ...
GLMM2-gamma_c    code-structured gemma-2-2b                   0.103469
                                 gemma-2-9b                   0.113348
                                 gemma-2b                     0.096256
                                 gemma-7b-it                  0.140691
                                 phi-2                        0.105917

                                                           boot_mean_log  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1             -0.770811
                                 Meta-Llama-3-8B               -0.708519
                                 Meta-Llama-3-8B-Instruct      -0.728287
                                 Mistral-7B-Instruct-v0.1      -0.692053
                                 Mistral-7B-Instruct-v0.3      -0.506964
...                                                                  ...
GLMM2-gamma_c    code-structured gemma-2-2b                    -0.020345
                                 gemma-2-9b                    -0.068651
                                 gemma-2b                      -0.032754
                                 gemma-7b-it                   -0.142654
                                 phi-2                         -0.002168

                                                           boot_median_log  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1               -0.753924
                                 Meta-Llama-3-8B                 -0.705076
                                 Meta-Llama-3-8B-Instruct        -0.729621
                                 Mistral-7B-Instruct-v0.1        -0.694678
                                 Mistral-7B-Instruct-v0.3        -0.506042
...                                                                    ...
GLMM2-gamma_c    code-structured gemma-2-2b                      -0.019548
                                 gemma-2-9b                      -0.066911
                                 gemma-2b                        -0.032001
                                 gemma-7b-it                     -0.141332
                                 phi-2                            0.003196

                                                           boot_p_value  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1             0.042021
                                 Meta-Llama-3-8B               0.026000
                                 Meta-Llama-3-8B-Instruct      0.078078
                                 Mistral-7B-Instruct-v0.1      0.025025
                                 Mistral-7B-Instruct-v0.3      0.072000
...                                                                 ...
GLMM2-gamma_c    code-structured gemma-2-2b                    0.838554
                                 gemma-2-9b                    0.538302
                                 gemma-2b                      0.731398
                                 gemma-7b-it                   0.308054
                                 phi-2                         0.980918

                                                           boot_n_requested  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                   2000.0
                                 Meta-Llama-3-8B                     2000.0
                                 Meta-Llama-3-8B-Instruct            2000.0
                                 Mistral-7B-Instruct-v0.1            2000.0
                                 Mistral-7B-Instruct-v0.3            2000.0
...                                                                     ...
GLMM2-gamma_c    code-structured gemma-2-2b                          2000.0
                                 gemma-2-9b                          2000.0
                                 gemma-2b                            2000.0
                                 gemma-7b-it                         2000.0
                                 phi-2                               2000.0

                                                           boot_n_failed  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                   0.0
                                 Meta-Llama-3-8B                     0.0
                                 Meta-Llama-3-8B-Instruct            0.0
                                 Mistral-7B-Instruct-v0.1            0.0
                                 Mistral-7B-Instruct-v0.3            0.0
...                                                                  ...
GLMM2-gamma_c    code-structured gemma-2-2b                          0.0
                                 gemma-2-9b                          0.0
                                 gemma-2b                            0.0
                                 gemma-7b-it                         0.0
                                 phi-2                               0.0

                                                           boot_n_nonconverged  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                         1.0
                                 Meta-Llama-3-8B                           0.0
                                 Meta-Llama-3-8B-Instruct                  2.0
                                 Mistral-7B-Instruct-v0.1                  2.0
                                 Mistral-7B-Instruct-v0.3                  0.0
...                                                                        ...
GLMM2-gamma_c    code-structured gemma-2-2b                              755.0
                                 gemma-2-9b                               68.0
                                 gemma-2b                                105.0
                                 gemma-7b-it                             299.0
                                 phi-2                                    61.0

                                                           boot_n_singular  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                     0.0
                                 Meta-Llama-3-8B                       0.0
                                 Meta-Llama-3-8B-Instruct              0.0
                                 Mistral-7B-Instruct-v0.1              0.0
                                 Mistral-7B-Instruct-v0.3              0.0
...                                                                    ...
GLMM2-gamma_c    code-structured gemma-2-2b                            0.0
                                 gemma-2-9b                            0.0
                                 gemma-2b                              0.0
                                 gemma-7b-it                           0.0
                                 phi-2                                 0.0

                                                           ...  wald_singular  \
test             prompt          model                     ...
GLMM1-is_variant GSM             Mathstral-7B-v0.1         ...          False
                                 Meta-Llama-3-8B           ...          False
                                 Meta-Llama-3-8B-Instruct  ...          False
                                 Mistral-7B-Instruct-v0.1  ...          False
                                 Mistral-7B-Instruct-v0.3  ...          False
...                                                        ...            ...
GLMM2-gamma_c    code-structured gemma-2-2b                ...          False
                                 gemma-2-9b                ...          False
                                 gemma-2b                  ...          False
                                 gemma-7b-it               ...          False
                                 phi-2                     ...          False

                                                           wald_nonconvergent  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                      False
                                 Meta-Llama-3-8B                        False
                                 Meta-Llama-3-8B-Instruct               False
                                 Mistral-7B-Instruct-v0.1               False
                                 Mistral-7B-Instruct-v0.3               False
...                                                                       ...
GLMM2-gamma_c    code-structured gemma-2-2b                              True
                                 gemma-2-9b                             False
                                 gemma-2b                               False
                                 gemma-7b-it                            False
                                 phi-2                                  False

                                                           wald_fit_failed  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                   False
                                 Meta-Llama-3-8B                     False
                                 Meta-Llama-3-8B-Instruct            False
                                 Mistral-7B-Instruct-v0.1            False
                                 Mistral-7B-Instruct-v0.3            False
...                                                                    ...
GLMM2-gamma_c    code-structured gemma-2-2b                          False
                                 gemma-2-9b                          False
                                 gemma-2b                            False
                                 gemma-7b-it                         False
                                 phi-2                               False

                                                           wald_ranef_variance  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                    6.464563
                                 Meta-Llama-3-8B                     11.253625
                                 Meta-Llama-3-8B-Instruct             9.954473
                                 Mistral-7B-Instruct-v0.1             5.064026
                                 Mistral-7B-Instruct-v0.3             6.984646
...                                                                        ...
GLMM2-gamma_c    code-structured gemma-2-2b                           7.946997
                                 gemma-2-9b                          16.748927
                                 gemma-2b                             6.274512
                                 gemma-7b-it                         16.217206
                                 phi-2                               18.875712

                                                           wald_ranef_sd  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1              2.542551
                                 Meta-Llama-3-8B                3.354642
                                 Meta-Llama-3-8B-Instruct       3.155071
                                 Mistral-7B-Instruct-v0.1       2.250339
                                 Mistral-7B-Instruct-v0.3       2.642848
...                                                                  ...
GLMM2-gamma_c    code-structured gemma-2-2b                     2.819042
                                 gemma-2-9b                     4.092545
                                 gemma-2b                       2.504898
                                 gemma-7b-it                    4.027059
                                 phi-2                          4.344619

                                                           wald_significant  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                     True
                                 Meta-Llama-3-8B                       True
                                 Meta-Llama-3-8B-Instruct              True
                                 Mistral-7B-Instruct-v0.1              True
                                 Mistral-7B-Instruct-v0.3             False
...                                                                     ...
GLMM2-gamma_c    code-structured gemma-2-2b                            True
                                 gemma-2-9b                           False
                                 gemma-2b                             False
                                 gemma-7b-it                          False
                                 phi-2                                False

                                                           wald_ci_width_log  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                  1.348435
                                 Meta-Llama-3-8B                    1.183447
                                 Meta-Llama-3-8B-Instruct           1.282309
                                 Mistral-7B-Instruct-v0.1           1.069828
                                 Mistral-7B-Instruct-v0.3           1.070019
...                                                                      ...
GLMM2-gamma_c    code-structured gemma-2-2b                         0.001717
                                 gemma-2-9b                         0.344386
                                 gemma-2b                           0.319036
                                 gemma-7b-it                        0.327059
                                 phi-2                              0.351703

                                                           agreement  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1              True
                                 Meta-Llama-3-8B                True
                                 Meta-Llama-3-8B-Instruct      False
                                 Mistral-7B-Instruct-v0.1       True
                                 Mistral-7B-Instruct-v0.3       True
...                                                              ...
GLMM2-gamma_c    code-structured gemma-2-2b                    False
                                 gemma-2-9b                     True
                                 gemma-2b                       True
                                 gemma-7b-it                    True
                                 phi-2                          True

                                                           width_ratio_log  \
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1                1.186312
                                 Meta-Llama-3-8B                  1.080180
                                 Meta-Llama-3-8B-Instruct         1.253495
                                 Mistral-7B-Instruct-v0.1         1.111993
                                 Mistral-7B-Instruct-v0.3         1.041480
...                                                                    ...
GLMM2-gamma_c    code-structured gemma-2-2b                     231.087015
                                 gemma-2-9b                       1.292585
                                 gemma-2b                         1.196496
                                 gemma-7b-it                      1.664280
                                 phi-2                            1.181142

                                                           bias_log
test             prompt          model
GLMM1-is_variant GSM             Mathstral-7B-v0.1        -0.012248
                                 Meta-Llama-3-8B          -0.009005
                                 Meta-Llama-3-8B-Instruct -0.007370
                                 Mistral-7B-Instruct-v0.1 -0.006858
                                 Mistral-7B-Instruct-v0.3 -0.005621
...                                                             ...
GLMM2-gamma_c    code-structured gemma-2-2b               -0.001179
                                 gemma-2-9b                0.005815
                                 gemma-2b                 -0.002371
                                 gemma-7b-it               0.003712
                                 phi-2                     0.000007

[180 rows x 29 columns]

In [49]:
def apply_tick(v):
    return r"\ding{51}" if v else r"\ding{56}"

mmm = boots_combined[~boots_combined.agreement][['boot_significant', 'wald_significant', 'wald_nonconvergent']]
mmm = mmm.reset_index()
mmm.insert(0, 'Test', mmm.test.apply(lambda s: f"{s[:4]} {s[4]}"))
mmm.insert(1, 'Effect', mmm.test.apply(lambda s: 'Variant' if s.endswith('variant') else r'$\gamma_c$'))
mmm.drop('test', inplace=True, axis=1)

mmm['boot_significant'] = mmm.boot_significant.apply(apply_tick)
mmm['wald_significant'] = mmm.wald_significant.apply(apply_tick)
mmm['wald_convergent'] = mmm.wald_nonconvergent.apply(lambda s: apply_tick(not s))
mmm.drop('wald_nonconvergent', inplace=True, axis=1)


bad_rows = []
bad_rows_idx = []
for idx, row in mmm.iterrows():
    if row['Test'] == 'GLMM 1' and row['prompt'] == 'GSM':
        continue
    if row['model'] not in significant_models:
        bad_rows.append(row)
        bad_rows_idx.append(idx)

mmm.drop(bad_rows_idx, inplace=True)

mmm = mmm.sort_values(['boot_significant', 'wald_convergent', 'prompt', 'model', 'Test', 'Effect'])

mmm = mmm.rename(
    columns={
        'wald_significant': "Wald",
        'boot_significant': "Bootstrap",
        'wald_convergent': "Convergent",
        'model': 'Model',
        'prompt': 'Prompt'
    }
)

mmm

,Test,Effect,Prompt,Model,Bootstrap,Wald,Convergent
7,GLMM 2,Variant,GSM,Mathstral-7B-v0.1,\ding{51},\ding{56},\ding{51}
4,GLMM 1,Variant,code-simple,Phi-3.5-mini-instruct,\ding{51},\ding{56},\ding{51}
13,GLMM 2,Variant,code-simple,Phi-3.5-mini-instruct,\ding{51},\ding{56},\ding{51}
0,GLMM 1,Variant,GSM,Meta-Llama-3-8B-Instruct,\ding{56},\ding{51},\ding{51}
15,GLMM 2,$\gamma_c$,GSM,gemma-2b,\ding{56},\ding{51},\ding{51}
9,GLMM 2,Variant,GSM,gemma-2b,\ding{56},\ding{51},\ding{51}
16,GLMM 2,$\gamma_c$,NL-simple,Meta-Llama-3-8B,\ding{56},\ding{51},\ding{51}
3,GLMM 1,Variant,code-simple,Meta-Llama-3-8B,\ding{56},\ding{51},\ding{51}
5,GLMM 1,Variant,code-simple,gemma-7b-it,\ding{56},\ding{51},\ding{51}
1,GLMM 1,Variant,GSM,gemma-2-2b,\ding{56},\ding{51},\ding{56}
10,GLMM 2,Variant,NL-simple,Mistral-7B-Instruct-v0.1,\ding{56},\ding{51},\ding{56}
11,GLMM 2,Variant,NL-structured,Phi-3.5-mini-instruct,\ding{56},\ding{51},\ding{56}
17,GLMM 2,$\gamma_c$,NL-structured,gemma-7b-it,\ding{56},\ding{51},\ding{56}
12,GLMM 2,Variant,NL-structured,gemma-7b-it,\ding{56},\ding{51},\ding{56}

In [51]:
print(pandas_to_latex(mmm, index=False, caption='Wald-to-bootstrap mismatch cases', label='tab:wald-mismatch', position='H'))

\begin{table}[H]
\caption{Wald-to-bootstrap mismatch cases}
\label{tab:wald-mismatch}
\begin{tabular}{lccccccc}
\toprule
Test & Effect & Prompt & Model & Bootstrap & Wald & Convergent \\
\midrule
GLMM 2 & Variant & GSM & Mathstral-7B-v0.1 & \ding{51} & \ding{56} & \ding{51} \\
GLMM 1 & Variant & code-simple & Phi-3.5-mini-instruct & \ding{51} & \ding{56} & \ding{51} \\
GLMM 2 & Variant & code-simple & Phi-3.5-mini-instruct & \ding{51} & \ding{56} & \ding{51} \\
GLMM 1 & Variant & GSM & Meta-Llama-3-8B-Instruct & \ding{56} & \ding{51} & \ding{51} \\
GLMM 2 & $\gamma_c$ & GSM & gemma-2b & \ding{56} & \ding{51} & \ding{51} \\
GLMM 2 & Variant & GSM & gemma-2b & \ding{56} & \ding{51} & \ding{51} \\
GLMM 2 & $\gamma_c$ & NL-simple & Meta-Llama-3-8B & \ding{56} & \ding{51} & \ding{51} \\
GLMM 1 & Variant & code-simple & Meta-Llama-3-8B & \ding{56} & \ding{51} & \ding{51} \\
GLMM 1 & Variant & code-simple & gemma-7b-it & \ding{56} & \ding{51} & \ding{51} \\
GLMM 1 & Variant & GSM & gemma-2-2b & \ding{56} & \ding{51} & \ding{56} \\
GLMM 2 & Variant & NL-simple & Mistral-7B-Instruct-v0.1 & \ding{56} & \ding{51} & \ding{56} \\
GLMM 2 & Variant & NL-structured & Phi-3.5-mini-instruct & \ding{56} & \ding{51} & \ding{56} \\
GLMM 2 & $\gamma_c$ & NL-structured & gemma-7b-it & \ding{56} & \ding{51} & \ding{56} \\
GLMM 2 & Variant & NL-structured & gemma-7b-it & \ding{56} & \ding{51} & \ding{56} \\
\bottomrule
\end{tabular}
\end{table}